import type { Deck } from './types';

// To add a passcode: SHA-256 hash it in the browser console:
//   await crypto.subtle.digest('SHA-256', new TextEncoder().encode('yourpassword'))
//     .then(b => Array.from(new Uint8Array(b)).map(n => n.toString(16).padStart(2,'0')).join(''))
// Then add the resulting hex string to passwordHashes below.
//
// Current passcode: "dustin2026"
// Replace with your real passcode before sharing.

/* ── Strategy column diagrams ──────────────────────────────────────────────
   Three 180x180 marks drawn in the deck's own vocabulary: dots, thin rules,
   circles. Gold-deep reads correctly on the beige light slides. All three are
   circular so they hold together as a set.                                  */

const G = '#b09055'; // --gold-deep

// A cluster of people connected to each other. Nine on a ring around a single
// hub, every connection generated by rule rather than picked by hand. Three
// layers, each doing a different job:
//   ring      the perimeter, neighbour to neighbour
//   skip-3    three large triangles passing at about half the radius, which
//             gives the middle of the mark some tangential structure
//   spokes    the hub connected to all nine, filling the interior radially
const _ring = (() => {
  const cx = 90, cy = 90, rOut = 70;
  const at = (r: number, deg: number) => {
    const a = ((deg - 90) * Math.PI) / 180;
    return [cx + r * Math.cos(a), cy + r * Math.sin(a)] as const;
  };
  const outer = Array.from({ length: 9 }, (_, i) => at(rOut, i * 40));
  const pts = [...outer, [cx, cy] as const];
  const edges: [number, number][] = [
    ...Array.from({ length: 9 }, (_, i) => [i, (i + 1) % 9] as [number, number]),
    ...Array.from({ length: 9 }, (_, i) => [i, (i + 3) % 9] as [number, number]),
    ...Array.from({ length: 9 }, (_, i) => [9, i] as [number, number]),
  ];
  const lines = edges.map(([a, b]) =>
    `<line x1="${pts[a][0].toFixed(1)}" y1="${pts[a][1].toFixed(1)}" x2="${pts[b][0].toFixed(1)}" y2="${pts[b][1].toFixed(1)}" stroke="${G}" stroke-width="1" opacity="0.32"/>`
  ).join('');
  const dots = pts.map(([x, y]) =>
    `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="5.5" fill="${G}"/>`
  ).join('');
  return `<svg viewBox="0 0 180 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A group of people connected to one another">${lines}${dots}</svg>`;
})();

// One circle built out of many identical circles. Uniform units, coherent whole.
const _grid = (() => {
  const rows = [3, 5, 7, 7, 7, 5, 3];
  const step = 23, cx = 90, y0 = 21;
  const dots = rows.flatMap((n, r) =>
    Array.from({ length: n }, (_, i) => {
      const x = cx - ((n - 1) * step) / 2 + i * step;
      return `<circle cx="${x}" cy="${y0 + r * step}" r="6" fill="${G}"/>`;
    })
  ).join('');
  return `<svg viewBox="0 0 180 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A circle built from a uniform grid of dots">${dots}</svg>`;
})();

// What it was, sitting inside what it could become.
const _vision = `<svg viewBox="0 0 180 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A small filled circle inside a much larger outlined circle"><circle cx="90" cy="90" r="76" fill="none" stroke="${G}" stroke-width="1.5" opacity="0.55"/><circle cx="90" cy="90" r="20" fill="${G}"/></svg>`;

export const webElevationDeck: Deck = {
  id: 'web-elevation',
  title: 'Web Experience Elevation',
  defaultTheme: 'light',
  passwordHashes: [
    // Same passcode as the gated work case studies (src/pages/work/tlife.astro)
    'd405e342c33ea8e0e1e65c2d94e5e8eeb8329e4d15fa6a7627de3e47f6cf1406',
  ],
  slides: [
    // 1 — Cover
    {
      type: 'cover',
      theme: 'light',
      label: 'Title',
      name: 'T-Mobile · Web Experience Elevation',
      headline: 'Nobody asked me to fix web. I <em>made the case</em> until it was mine.',
      visual: '/deck/assets/web-elevation/cover.png',
      badge: '/deck/assets/web-elevation/tmobile-badge.png',
    },

    // 2 — The situation
    {
      type: 'bullets',
      theme: 'light',
      label: 'The situation',
      eyebrow: 'Web elevation · the situation',
      headline: 'Web was the forgotten surface.',
      sub: 'Most companies have a surface that slowly stops getting attention, and at T-Mobile that was the web experience.',
      cards: true,
      bullets: [
        {
          title: 'The app was the priority',
          body: 'Most of the investment and most of the attention went to the app, and web was left inconsistent and under-resourced, with nobody owning the quality bar across teams.',
        },
        {
          title: 'Ownership was split across teams',
          body: "It wasn't really neglect. Several managers, myself included, each owned a piece of the web experience, and because nobody owned the whole thing, nothing stayed consistent and the ambition stayed low.",
        },
        {
          title: 'I kept bringing evidence',
          body: 'This had been the situation for about two years and nobody had asked me to take it on, so I kept bringing evidence that web was fragmented until my VP decided to hand me the whole thing.',
        },
        {
          title: 'There was no playbook',
          body: 'There was no playbook for this kind of work, so I got to build one. That meant deciding what the approach should be, what the standards were, and what web could become.',
        },
      ],
    },

    // 3 — Strategy (3 cards)
    {
      type: 'values',
      theme: 'light',
      label: 'The strategy',
      eyebrow: 'Web elevation · the strategy',
      headline: 'The playbook came down to three things.',
      cols: [
        {
          title: 'Build accountability',
          graphic: _ring,
          body: 'I brought together the principals from every team that touched web and had them set the quality bar first, before I asked anyone else to meet it.',
        },
        {
          title: 'Create standards and governance',
          graphic: _grid,
          body: 'Teams needed something concrete to work from, so we created a governance role, built a toolkit, and wrote down the standards.',
        },
        {
          title: 'Define the vision',
          graphic: _vision,
          body: 'Fixing what was already there wasn\'t enough, so I hired a principal whose only job was to define what web could become.',
        },
      ],
    },

    // 4A — Cross-team accountability
    {
      type: 'bullets',
      theme: 'light',
      label: 'Cross-team accountability',
      eyebrow: 'Web elevation · accountability',
      headline: "I started with the people who'd have to hold the bar.",
      bullets: [
        'I pulled together the principals from every team that touched web and made that group the core: Foundations, Design Systems, Commerce, T-Mobile for Business, Frontline and Assisted, and Service.',
        'We ran a weekly web crit that the principals led, and it was open to every designer across every team.',
        "That gave us a kind of cross-team accountability that hadn't existed before.",
      ],
      stats: [
        { value: '7', label: 'Principal product designers' },
        { value: '6', label: 'Different teams' },
        { value: '100%', label: 'Designer participation in weekly crit' },
      ],
    },

    // 4B — Standards + governance
    {
      type: 'bullets',
      theme: 'light',
      label: 'Standards + governance',
      eyebrow: 'Web elevation · standards',
      headline: "Standards don't hold unless somebody owns them.",
      bullets: [
        "I created a Principal of Web Governance and Information Architecture, a role that didn't exist before, to own the standards, the components, and how the whole thing was organized.",
        'That person partnered with the design system team to audit where the gaps were and build the plan to close them.',
        'We shipped the first version of the web toolkit within 90 days, added 15 new and refined components to the design system, and got every new web design onto standard breakpoints.',
        'We also launched a global nav redesign, which built alignment across business, product, and marketing on a system that could scale as new products and AI entry points came in.',
      ],
      artifact: {
        src: '/deck/assets/web-elevation/team-structure.png',
        caption: 'How the web team was structured, shown to the team once the governance and vision roles were in place.',
      },
    },

    // 4C — Web vision
    {
      type: 'bullets',
      theme: 'light',
      label: 'Web vision',
      eyebrow: 'Part three',
      headline: 'I hired a Principal whose only job was to define what T-Mobile web could become.',
      bullets: [
        'Brought in Vidal Men with a specific mandate: define what web could be.',
        'Month one: established the web design principles the entire surface should work from.',
        'Evolved into a forward-looking prospect journey vision.',
        'Research-grounded, stakeholder-aligned, and used as the north star for future web investments.',
      ],
    },

    // 5 — What it unlocked
    {
      type: 'unlock',
      theme: 'light',
      label: 'What it unlocked',
      headline: "From nobody's job to a VP priority in six months.",
      bullets: [
        "Vidal's vision work got the attention of my VP.",
        'There was no homepage redesign planned. The vision created one, and Marketing partnered with us to lead it.',
        'That led to something bigger: a formal tiger team to build the next-generation T-Mobile web system.',
      ],
      subsection: {
        title: 'The Web Vision Tiger Team',
        items: [
          '6-week sprint cadence',
          '4 flagship web experiences in scope',
          'Weekly VP review · Daily Director alignment',
          'Multi-brand: T-Mobile, Mint, Metro',
        ],
      },
    },

    // 6 — The work (homepage redesign screenshots)
    // Add images to public/deck/assets/web-elevation/ and update the paths below.
    {
      type: 'product',
      theme: 'light',
      label: 'The work',
      eyebrow: 'Web Vision Tiger Team · in progress',
      headline: 'Some of the most ambitious design work of my T-Mobile tenure.',
      body: 'Modern, cohesive design direction for the full t-mobile.com experience. AI-integrated search, responsive-first, and a modular system built to scale across brands. In progress at time of layoff.',
      footer: 'Design direction shown. Not representative of final shipped direction.',
      images: [
        '/deck/assets/web-elevation/homepage-mobile-1.png',
        '/deck/assets/web-elevation/homepage-mobile-2.png',
      ],
    },

    // 7 — Key outcomes
    {
      type: 'metrics',
      theme: 'light',
      label: 'Key outcomes',
      eyebrow: 'Results',
      headline: 'Craft + culture + momentum.',
      cards: [
        {
          number: '90',
          label: 'Days to ship',
          description: 'v1 Web Toolkit built and shipped within 90 days of kickoff.',
        },
        {
          number: '100%',
          label: 'Crit participation',
          description: 'Weekly web crits running with full participation across all teams.',
        },
        {
          number: '6 mo',
          label: 'Campaign to mandate',
          description: 'From surfacing evidence nobody asked for to VP involvement and a homepage redesign that did not exist before.',
        },
      ],
    },
  ],
};
