import type { Deck } from './types';

// To add a passcode: SHA-256 hash it in the browser console:
//   await crypto.subtle.digest('SHA-256', new TextEncoder().encode('yourpassword'))
//     .then(b => Array.from(new Uint8Array(b)).map(n => n.toString(16).padStart(2,'0')).join(''))
// Then add the resulting hex string to passwordHashes below.
//
// Current passcode: "dustin2026"
// Replace with your real passcode before sharing.

/* ── Strategy column diagrams ──────────────────────────────────────────────
   Three 180x180 marks drawn in the deck's own vocabulary: dots, thin rules,
   circles. Gold-deep reads correctly on the beige light slides. All three are
   circular so they hold together as a set.                                  */

const G = '#b09055'; // --gold-deep

// A cluster of people connected to each other. Nine on a ring around a single
// hub, every connection generated by rule rather than picked by hand. Three
// layers, each doing a different job:
//   ring      the perimeter, neighbour to neighbour
//   skip-3    three large triangles passing at about half the radius, which
//             gives the middle of the mark some tangential structure
//   spokes    the hub connected to all nine, filling the interior radially
const _ring = (() => {
  const cx = 90, cy = 90, rOut = 70;
  const at = (r: number, deg: number) => {
    const a = ((deg - 90) * Math.PI) / 180;
    return [cx + r * Math.cos(a), cy + r * Math.sin(a)] as const;
  };
  const outer = Array.from({ length: 9 }, (_, i) => at(rOut, i * 40));
  const pts = [...outer, [cx, cy] as const];
  const edges: [number, number][] = [
    ...Array.from({ length: 9 }, (_, i) => [i, (i + 1) % 9] as [number, number]),
    ...Array.from({ length: 9 }, (_, i) => [i, (i + 3) % 9] as [number, number]),
    ...Array.from({ length: 9 }, (_, i) => [9, i] as [number, number]),
  ];
  const lines = edges.map(([a, b]) =>
    `<line x1="${pts[a][0].toFixed(1)}" y1="${pts[a][1].toFixed(1)}" x2="${pts[b][0].toFixed(1)}" y2="${pts[b][1].toFixed(1)}" stroke="${G}" stroke-width="1" opacity="0.32"/>`
  ).join('');
  const dots = pts.map(([x, y]) =>
    `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="5.5" fill="${G}"/>`
  ).join('');
  return `<svg viewBox="0 0 180 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A group of people connected to one another">${lines}${dots}</svg>`;
})();

// One circle built out of many identical circles. Uniform units, coherent whole.
const _grid = (() => {
  const rows = [3, 5, 7, 7, 7, 5, 3];
  const step = 23, cx = 90, y0 = 21;
  const dots = rows.flatMap((n, r) =>
    Array.from({ length: n }, (_, i) => {
      const x = cx - ((n - 1) * step) / 2 + i * step;
      return `<circle cx="${x}" cy="${y0 + r * step}" r="6" fill="${G}"/>`;
    })
  ).join('');
  return `<svg viewBox="0 0 180 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A circle built from a uniform grid of dots">${dots}</svg>`;
})();

// What it was, sitting inside what it could become.
const _vision = `<svg viewBox="0 0 180 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A small filled circle inside a much larger outlined circle"><circle cx="90" cy="90" r="76" fill="none" stroke="${G}" stroke-width="1.5" opacity="0.55"/><circle cx="90" cy="90" r="20" fill="${G}"/></svg>`;

const A = '/deck/assets/web-elevation';

export const webElevationDeck: Deck = {
  id: 'web-elevation',
  title: 'Web Experience Elevation',
  defaultTheme: 'light',
  passwordHashes: [
    // Same passcode as the gated work case studies (src/pages/work/tlife.astro)
    'd405e342c33ea8e0e1e65c2d94e5e8eeb8329e4d15fa6a7627de3e47f6cf1406',
  ],
  slides: [
    // 1 · Cover
    {
      type: 'cover',
      theme: 'light',
      label: 'Title',
      name: 'T-Mobile · Web Experience Elevation',
      headline: 'Nobody asked me to fix web. I <em>made the case</em> until it was mine.',
      visual: `${A}/cover.png`,
      badge: `${A}/tmobile-badge.png`,
    },

    // 2 · The situation: numbers left, customer voices right
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="The situation">
    <div class="content">
      <div class="we-cols" style="grid-template-columns:2fr 1fr">
        <div class="we-text">
          <p class="eyebrow rise">Web elevation · the situation</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">Web was the forgotten surface.</h2>
          <div class="we-body">
          <div class="we-facts">
            <div class="we-fact rise d3"><p class="num">#2</p><p>“Website” was the second most mentioned phrase in customer feedback, and it wasn’t positive</p></div>
            <div class="we-fact rise d4"><p class="num">10%</p><p>of customers start self-service on web</p></div>
            <div class="we-fact rise d5"><p class="num">0</p><p>owners for the whole experience. Several managers each owned a piece.</p></div>
          </div>
          </div>
        </div>
        <div class="we-vis we-quotes">
          <figure class="we-say rise d3"><div class="we-card we-quote"><p class="q">You guys keep changing the website and when I try to look up data, call, and message logs it’s more difficult every time.</p></div><figcaption>T-Mobile customer, via Qualtrics</figcaption></figure>
          <figure class="we-say rise d4"><div class="we-card we-quote"><p class="q">This website is not user friendly and I have now spent 2 days trying to get our protection plans cancelled.</p></div><figcaption>T-Mobile customer, via Qualtrics</figcaption></figure>
          <figure class="we-say rise d5"><div class="we-card we-quote"><p class="q">Your website directs me to the app that is obsolete.</p></div><figcaption>T-Mobile customer, via Qualtrics</figcaption></figure>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 3 · The fragmentation: the cause, with one prominent example and the customer voice
    // Sources: unify navigation deck page 21 (screenshots); UX architect role proposal, IMG_1175's sibling IMG_1176 (18% stat and quote).
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="The fragmentation">
    <div class="content">
      <div class="we-cols" style="grid-template-columns:1fr 2fr">
        <div class="we-text">
          <p class="eyebrow rise" style="white-space:nowrap">Web elevation · the fragmentation</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">Every team built web its own way.</h2>
          <div class="we-body">
          <ul class="we-list">
            <li class="rise d3">Navigation changed depending on where you entered</li>
            <li class="rise d4">No shared breakpoints</li>
            <li class="rise d5">No shared web toolkit</li>
          </ul>
          </div>
        </div>
        <div class="we-vis">
          <p class="we-cap rise d3">Example: homepage to Home Internet</p>
          <div class="we-card rise d3"><img src="${A}/nav-journey-home.jpg" alt="T-Mobile homepage header"></div>
          <div class="we-arrow rise d4" style="height:56px"><span style="height:34px"></span></div>
          <div class="we-card rise d4"><img src="${A}/nav-journey-internet.jpg" alt="One click later, the Home Internet page has a different logo and navigation"></div>
          <div class="we-voice rise d5">
            <div class="we-stat"><p class="num">18%</p><p>of users report navigation difficulties</p></div>
            <figure class="we-say"><div class="we-card we-quote"><p class="q">Your website sucks and is circular.</p></div><figcaption>T-Mobile customer</figcaption></figure>
          </div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 4 · Strategy (3 cards)
    {
      type: 'values',
      theme: 'light',
      label: 'The strategy',
      eyebrow: 'Web elevation · the strategy',
      headline: 'The playbook came down to three things.',
      cols: [
        {
          title: 'Build accountability',
          graphic: _ring,
          body: '7 principals across 6 teams ran a weekly web studio. All web work went through it before it reached a VP.',
        },
        {
          title: 'Create standards and governance',
          graphic: _grid,
          body: 'Teams needed something concrete to work from, so we created a governance role, built a toolkit, and wrote down the standards.',
        },
        {
          title: 'Define the vision',
          graphic: _vision,
          body: 'Fixing what was already there wasn\'t enough, so I hired a principal whose only job was to define what web could become.',
        },
      ],
    },

    // 5 · Standards: two artifacts from the proposal to Dustin's VP, told as two separate points.
    // Left: the web lead and governance role (IMG_1175). Right: the proposed structure (2026 kickoff screens/team-structure.png).
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="Standards">
    <div class="content">
      <p class="eyebrow rise">Web elevation · standards and governance</p>
      <h2 class="head-lg rise d2" style="margin-top:26px">Standards need an owner.</h2>
      <div class="we-pair">
        <div class="rise d3">
          <p class="we-cap">The proposal</p>
          <div class="we-card"><img src="${A}/role-case.jpg" alt="The proposal for a web lead and governance role"></div>
        </div>
        <div class="rise d4">
          <p class="we-cap">New structure</p>
          <div class="we-card"><img src="${A}/team-structure-proposal.png" alt="Proposed web team structure, with web governance and navigation highlighted"></div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 6 · Unifying navigation
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="Navigation">
    <div class="content">
      <div class="we-cols" style="grid-template-columns:600px 1fr">
        <div class="we-text">
          <p class="eyebrow rise">Web elevation · navigation</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">One navigation, no matter where you enter.</h2>
          <div class="we-body">
          <ul class="we-list">
            <li class="rise d3">One primary navigation across every line of business</li>
            <li class="rise d4">Designed for desktop and mobile web</li>
          </ul>
          <div class="we-big rise d5"><p class="num">$5M to $7.3M</p><p>Projected additional revenue a year, from 5.3K to 7.9K more postpaid orders</p></div>
          </div>
        </div>
        <div class="we-vis we-navstack">
          <div class="we-card desk rise d3"><img src="${A}/nav-desktop.jpg" alt="Unified desktop navigation with mega menu"></div>
          <div class="we-card mob rise d5"><img src="${A}/nav-mobile.jpg" alt="Unified mobile web navigation"></div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 7 · Defining the vision: concept direction, auto-scrolling
    // Scroll distance in deck-custom.css (weScroll) = track height (2827px at 880w) minus view (600px).
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="The vision">
    <div class="content">
      <div class="we-cols" style="grid-template-columns:640px 1fr">
        <div class="we-text">
          <p class="eyebrow rise">Web elevation · the vision</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">I hired a principal designer to define what web could become.</h2>
          <div class="we-body">
          <ul class="we-list">
            <li class="rise d3">Month one: design principles for all of web</li>
            <li class="rise d4">Next: a vision for the full prospect journey</li>
            <li class="rise d5">Leadership reviewed it next to two agency concepts</li>
          </ul>
          </div>
        </div>
        <div class="we-vis rise d3" style="justify-self:end">
          <p class="we-cap">Concept direction</p>
          <div class="we-browser we-scroll">
            <div class="bar"><i></i><i></i><i></i></div>
            <div class="view"><div class="track">
              <img src="${A}/concept-top.jpg" alt="Homepage concept, top of page">
              <img src="${A}/concept-plans.jpg" alt="Homepage concept, plans and benefits">
            </div></div>
          </div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 8 · What it unlocked
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="What it unlocked">
    <div class="content">
      <div class="we-cols" style="grid-template-columns:680px 1fr">
        <div class="we-text">
          <p class="eyebrow rise">Web elevation · what it unlocked</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">Web became a priority.</h2>
          <div class="we-body">
          <ul class="we-list">
            <li class="rise d3">A homepage redesign that wasn’t on any roadmap</li>
            <li class="rise d3">Marketing partnered with design to lead it</li>
            <li class="rise d4">A formal Web Vision Tiger Team</li>
          </ul>
          <div class="we-sublist rise d5">
            <p>The tiger team</p>
            <ul>
              <li>6-week sprints</li>
              <li>4 flagship experiences</li>
              <li>Weekly VP review</li>
              <li>T-Mobile, Mint, and Metro</li>
            </ul>
          </div>
          </div>
        </div>
        <div class="we-vis we-deckstack">
          <div class="we-card back rise d3"><img src="${A}/tiger-cover.jpg" alt="Web Vision Tiger Team delivery framework cover"></div>
          <div class="we-card front rise d4"><img src="${A}/tiger-scope.jpg" alt="Tiger team scope across four flagship experiences"></div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 9 · What's live today
    // TODO(claim): headline and results wording are drafts. Dustin parked how to
    // describe results that came after he left. Revisit once he has seen this slide.
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="Live today">
    <div class="content">
      <div class="we-live">
        <div class="we-text">
          <p class="eyebrow rise">Web elevation · live today</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">The new <span style="white-space:nowrap">t-mobile.com</span> homepage.</h2>
          <div class="we-body">
          <ul class="we-list">
            <li class="rise d3">Rolled out in stages, starting at 2% of traffic</li>
            <li class="rise d4">Direct navigation engagement up nearly 70%</li>
            <li class="rise d4">Bounce rate down, time on page up</li>
          </ul>
          <div class="we-before rise d5">
            <p class="we-cap">Before</p>
            <div class="we-card"><img src="${A}/homepage-before.jpg" alt="The previous t-mobile.com homepage"></div>
          </div>
          </div>
        </div>
        <div class="we-vis rise d3">
          <p class="we-cap">Now</p>
          <div class="we-browser we-video">
            <div class="bar"><i></i><i></i><i></i></div>
            <div class="view"><video src="${A}/homepage-scroll.mp4" poster="${A}/homepage-after-poster.jpg" autoplay muted loop playsinline preload="metadata"></video></div>
          </div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 10 · Results
    // TODO(claim): the homepage column depends on the same parked wording question.
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="Results">
    <div class="content">
      <p class="eyebrow rise">Web elevation · results</p>
      <h2 class="head-lg rise d2" style="margin-top:26px">Web became everyone’s job.</h2>
      <div class="we-results">
        <div class="we-res rise d2"><p class="l">Accountability</p><p class="num">100%</p><p class="d">of web work tracked through the studio. 7 principals across 6 teams.</p></div>
        <div class="we-res rise d3"><p class="l">Standards</p><p class="num">90 days</p><p class="d">to toolkit v1. 15 components. 100% of new designs on standard breakpoints.</p></div>
        <div class="we-res rise d4"><p class="l">Navigation</p><p class="num">$5M+</p><p class="d">projected a year, up to $7.3M, from one navigation across every line of business.</p></div>
        <div class="we-res rise d5"><p class="l">Vision</p><p class="num">4</p><p class="d">flagship experiences in a formal tiger team, across 3 brands.</p></div>
        <div class="we-res rise d6"><p class="l">Homepage</p><p class="num">Live</p><p class="d">on t-mobile.com. Direct navigation engagement up nearly 70%.</p></div>
      </div>
    </div>
  </section>`,
    },
  ],
};
