import type { Deck } from './types';

// To add a passcode: SHA-256 hash it in the browser console:
//   await crypto.subtle.digest('SHA-256', new TextEncoder().encode('yourpassword'))
//     .then(b => Array.from(new Uint8Array(b)).map(n => n.toString(16).padStart(2,'0')).join(''))
// Then add the resulting hex string to passwordHashes below.
//
// Current passcode: "dustin2026"
// Replace with your real passcode before sharing.

/* ── Strategy column diagrams ──────────────────────────────────────────────
   Three 180x180 marks drawn in the deck's own vocabulary: dots, thin rules,
   circles. Gold-deep reads correctly on the beige light slides. All three are
   circular so they hold together as a set.                                  */

const G = '#b09055'; // --gold-deep

// A cluster of people connected to each other. Nine on a ring around a single
// hub, every connection generated by rule rather than picked by hand. Three
// layers, each doing a different job:
//   ring      the perimeter, neighbour to neighbour
//   skip-3    three large triangles passing at about half the radius, which
//             gives the middle of the mark some tangential structure
//   spokes    the hub connected to all nine, filling the interior radially
const _ring = (() => {
  const cx = 90, cy = 90, rOut = 70;
  const at = (r: number, deg: number) => {
    const a = ((deg - 90) * Math.PI) / 180;
    return [cx + r * Math.cos(a), cy + r * Math.sin(a)] as const;
  };
  const outer = Array.from({ length: 9 }, (_, i) => at(rOut, i * 40));
  const pts = [...outer, [cx, cy] as const];
  const edges: [number, number][] = [
    ...Array.from({ length: 9 }, (_, i) => [i, (i + 1) % 9] as [number, number]),
    ...Array.from({ length: 9 }, (_, i) => [i, (i + 3) % 9] as [number, number]),
    ...Array.from({ length: 9 }, (_, i) => [9, i] as [number, number]),
  ];
  const lines = edges.map(([a, b]) =>
    `<line x1="${pts[a][0].toFixed(1)}" y1="${pts[a][1].toFixed(1)}" x2="${pts[b][0].toFixed(1)}" y2="${pts[b][1].toFixed(1)}" stroke="${G}" stroke-width="1" opacity="0.32"/>`
  ).join('');
  const dots = pts.map(([x, y]) =>
    `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="5.5" fill="${G}"/>`
  ).join('');
  return `<svg viewBox="0 0 180 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A group of people connected to one another">${lines}${dots}</svg>`;
})();

// One circle built out of many identical circles. Uniform units, coherent whole.
const _grid = (() => {
  const rows = [3, 5, 7, 7, 7, 5, 3];
  const step = 23, cx = 90, y0 = 21;
  const dots = rows.flatMap((n, r) =>
    Array.from({ length: n }, (_, i) => {
      const x = cx - ((n - 1) * step) / 2 + i * step;
      return `<circle cx="${x}" cy="${y0 + r * step}" r="6" fill="${G}"/>`;
    })
  ).join('');
  return `<svg viewBox="0 0 180 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A circle built from a uniform grid of dots">${dots}</svg>`;
})();

// What it was, sitting inside what it could become.
const _vision = `<svg viewBox="0 0 180 180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A small filled circle inside a much larger outlined circle"><circle cx="90" cy="90" r="76" fill="none" stroke="${G}" stroke-width="1.5" opacity="0.55"/><circle cx="90" cy="90" r="20" fill="${G}"/></svg>`;

const A = '/deck/assets/web-elevation';

export const webElevationDeck: Deck = {
  id: 'web-elevation',
  title: 'Web Experience Elevation',
  defaultTheme: 'light',
  // Injected into every slide but the cover by src/pages/deck/[id].astro.
  runningHead: 'Web Experience Elevation',
  passwordHashes: [
    // Same passcode as the gated work case studies (src/pages/work/tlife.astro)
    'd405e342c33ea8e0e1e65c2d94e5e8eeb8329e4d15fa6a7627de3e47f6cf1406',
  ],
  slides: [
    // 1 · Cover
    {
      type: 'cover',
      theme: 'light',
      label: 'Title',
      name: 'T-Mobile · Web Experience Elevation',
      headline: 'Nobody asked me to fix web. I <em>made the case</em> until it was mine',
      visual: `${A}/cover.png`,
      badge: `${A}/tmobile-badge.png`,
    },

    // 2 · The situation: numbers left, customer voices right
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="The situation">
    <div class="orbs" data-orb-tone="light" data-orb-side="left" data-orb-style="rings"></div>
    <div class="content">
      <div class="we-cols we-2-1">
        <div class="we-text">
          <p class="eyebrow rise">The situation</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">Web was the forgotten surface</h2>
          <div class="we-body">
          <div class="we-facts">
            <div class="we-fact rise d3"><p class="num">#2</p><p>“Website” was the second most mentioned phrase in customer feedback, and it wasn’t positive</p></div>
            <div class="we-fact rise d4"><p class="num">18%</p><p>of users report navigation difficulties</p></div>
            <div class="we-fact rise d5"><p class="num">0</p><p>owners for the whole experience. Several managers each owned a piece.</p></div>
          </div>
          </div>
        </div>
        <div class="we-vis we-quotes">
          <figure class="we-say rise d3"><div class="we-card we-quote"><p class="q">You guys keep changing the website and when I try to look up data, call, and message logs it’s more difficult every time.</p></div><figcaption>T-Mobile customer, via Qualtrics</figcaption></figure>
          <figure class="we-say rise d4"><div class="we-card we-quote"><p class="q">This website is not user friendly and I have now spent 2 days trying to get our protection plans cancelled.</p></div><figcaption>T-Mobile customer, via Qualtrics</figcaption></figure>
          <figure class="we-say rise d5"><div class="we-card we-quote"><p class="q">Your website directs me to the app that is obsolete.</p></div><figcaption>T-Mobile customer, via Qualtrics</figcaption></figure>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 3 · The fragmentation: text on beige, three lines of business navs bleeding off a stone panel, customer quote
    // Layout from Dustin's Figma (Case study preso v4, node 18:92). Quote from IMG_1176; the 18% stat moved to slide 2.
    {
      type: 'raw',
      html: `
  <section class="slide light we we-frag" data-label="The fragmentation">
    <div class="we-frag-text">
      <p class="eyebrow rise">The fragmentation</p>
      <h2 class="head-lg rise d2" style="margin-top:26px">Every team built web its own way</h2>
      <ul class="we-list">
        <li class="rise d3">Navigation changed depending on where you entered</li>
        <li class="rise d4">Breakpoints were inconsistent across teams</li>
        <li class="rise d5">Limited design system components and no shared Figma toolkit</li>
      </ul>
    </div>
    <div class="we-frag-panel">
      <div class="we-frag-navs rise d3">
        <img src="${A}/nav-business.png" alt="T-Mobile for Business navigation">
        <img src="${A}/nav-wireless.png" alt="T-Mobile wireless navigation">
        <img src="${A}/nav-internet.png" alt="5G Home Internet navigation, with a different logo and menu">
        <p class="we-cap">Multiple navigations across our lines of business</p>
      </div>
      <figure class="we-say we-frag-say rise d5"><div class="we-card we-quote"><p class="q">Your website sucks and is circular.</p></div><figcaption>T-Mobile customer, via Qualtrics</figcaption></figure>
    </div>
  </section>`,
    },

    // 4 · Strategy (3 cards)
    {
      type: 'values',
      theme: 'light',
      label: 'The strategy',
      eyebrow: 'The strategy',
      headline: 'The playbook came down to three things',
      cols: [
        {
          title: 'Build accountability',
          graphic: _ring,
          body: '7 principals across 6 teams ran a weekly web studio. All web work went through it before it reached a VP.',
        },
        {
          title: 'Create standards and governance',
          graphic: _grid,
          body: 'Teams needed something concrete to work from, so we created a governance role, built a toolkit, and wrote down the standards.',
        },
        {
          title: 'Define the vision',
          graphic: _vision,
          body: 'Fixing what was already there wasn\'t enough, so I hired a principal whose only job was to define what web could become.',
        },
      ],
    },

    // 5 · Standards: two artifacts from the proposal to Dustin's VP, told as two separate points.
    // Left: the web lead and governance role (IMG_1175). Right: the proposed structure (2026 kickoff screens/team-structure.png).
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="Standards">
    <div class="content">
      <p class="eyebrow rise">Laying the foundation</p>
      <h2 class="head-lg rise d2" style="margin-top:26px">Standards need an owner</h2>
      <div class="we-pair">
        <div class="rise d3">
          <p class="we-cap">The proposal</p>
          <div class="we-card"><img src="${A}/role-case.jpg" alt="The proposal for a web lead and governance role"></div>
        </div>
        <div class="rise d4">
          <p class="we-cap">New structure</p>
          <div class="we-card"><img src="${A}/team-structure-proposal.png" alt="Proposed web team structure, with web governance and navigation highlighted"></div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 6 · Unifying navigation
    {
      type: 'raw',
      html: `
  <section class="slide dark we we-nav6" data-label="Navigation">
    <div class="content">
      <div class="we-nav6-head">
        <div>
          <p class="eyebrow rise">Navigation</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">Unify navigation across all products and services</h2>
        </div>
        <div class="we-nav6-stat rise d3">
          <p class="num">$5M to $7.3M</p>
          <p>Projected additional revenue a year, from 5.3K to 7.9K more postpaid orders</p>
        </div>
      </div>
      <div class="we-nav6-body">
        <p class="we-cap rise d3">Concept exploration</p>
        <div class="we-nav6-figs">
          <img class="rise d4" src="${A}/nav-desktop-annotated.png" alt="Desktop mega menu concept, annotated: AI search, unified nav integrated into Plans, Internet, T-Life entry, promo slot, all lines of business in one location">
          <img class="rise d5" src="${A}/nav-mobile-annotated.png" alt="Mobile navigation concept across three screens, annotated: AI search, Internet added, cart, all lines of business in one unified location, displays without scroll">
        </div>
      </div>
    </div>
  </section>`,
    },

    // 7 · Defining the vision: homepage concept exploration, auto-scrolling
    // Scroll distance in deck-custom.css (weScroll) = track height (2529px at 780w, a half column) minus view (600px).
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="The vision">
    <div class="content">
      <div class="we-cols we-1-1">
        <div class="we-text">
          <p class="eyebrow rise">Looking forward</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">I hired to define the vision</h2>
          <div class="we-body">
          <ul class="we-list">
            <li class="rise d3">Design principles for all of web, inside the first month</li>
            <li class="rise d4">Then a vision for the full prospect journey</li>
          </ul>
          </div>
        </div>
        <div class="we-vis rise d3">
          <p class="we-cap">Homepage concept exploration</p>
          <div class="we-browser we-scroll">
            <div class="bar"><i></i><i></i><i></i></div>
            <div class="view"><div class="track">
              <img src="${A}/concept-full.jpg" alt="Homepage concept, full page: hero, brand and benefit cards, switching offers, device grid, and plan pricing">
            </div></div>
          </div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 8 · What it unlocked
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="What it unlocked">
    <div class="content">
      <div class="we-cols we-1-1">
        <div class="we-vis we-deckstack">
          <div class="we-card back rise d3"><img src="${A}/tiger-purpose.jpg" alt="Tiger team purpose: building the next-generation T-Mobile web system, anchored in four flagship experiences"></div>
          <div class="we-card front rise d4"><img src="${A}/tiger-goals.jpg" alt="Tiger team goals: modernize craft and system readiness, expand web experience direction, accelerate new design implementation, scale patterns and components across brands"></div>
        </div>
        <div class="we-text">
          <p class="eyebrow rise">What it unlocked</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">Web became a priority</h2>
          <div class="we-body">
          <ul class="we-list">
            <li class="rise d3">A homepage redesign that wasn’t on any roadmap</li>
            <li class="rise d3">Marketing partnered with design to lead it</li>
            <li class="rise d4">A formal Web Vision Tiger Team</li>
          </ul>
          </div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 9 · What's live today
    // Bullets are the five design changes from the homepage strategy doc's executive
    // summary (points 01-05, with 04 and 05 merged). The metric is point 07, captioned
    // with its source: the homepage shipped after the layoff and the numbers belong to
    // the strategy doc, so the slide cites rather than claims. See the Act Three
    // attribution rule in web-elevation-outline.md.
    {
      type: 'raw',
      html: `
  <section class="slide light we we-live" data-label="Live today">
    <div class="content">
      <div class="we-live-head">
        <div>
          <p class="eyebrow rise">Live today</p>
          <h2 class="head-lg rise d2" style="margin-top:26px">New <span style="white-space:nowrap">t-mobile.com</span> homepage</h2>
        </div>
        <div class="we-live-stat rise d3">
          <p class="num">Nearly 70%</p>
          <p class="d">More direct navigation engagement.<br>Bounce rate down, dwell time up.</p>
          <p class="we-cap">Currently testing 20% of traffic</p>
        </div>
      </div>
      <div class="we-live-body">
        <ul class="we-list">
          <li class="rise d3">Promotion-led to value-led positioning</li>
          <li class="rise d4">A progressive story, not stacked promotional billboards</li>
          <li class="rise d5">Content adapts to what’s known about the customer</li>
          <li class="rise d5">Commerce throughout, with high-intent paths protected</li>
        </ul>
        <div class="we-live-vis">
          <div class="now rise d3">
            <div class="we-browser we-video">
              <div class="bar"><i></i><i></i><i></i></div>
              <div class="view"><video src="${A}/homepage-scroll.mp4" poster="${A}/homepage-after-poster.jpg" autoplay muted loop playsinline preload="metadata"></video></div>
            </div>
          </div>
          <div class="before rise d5">
            <div class="we-card"><img src="${A}/homepage-before.jpg" alt="The previous t-mobile.com homepage"></div>
            <p class="we-cap">Before</p>
          </div>
        </div>
      </div>
    </div>
  </section>`,
    },

    // 10 · Results
    // Four cards, one per initiative. The homepage card was removed: the ship is now
    // carried by the Vision card (it is what the vision produced) and the nav engagement
    // lift sits on the Navigation card as early validation of that workstream's thesis.
    {
      type: 'raw',
      html: `
  <section class="slide light we" data-label="Results">
    <div class="content">
      <p class="eyebrow rise">Results</p>
      <h2 class="head-lg rise d2" style="margin-top:26px">Web became everyone’s job</h2>
      <div class="we-results">
        <div class="we-res rise d2"><p class="l">Accountability</p><p class="num">100%</p><p class="d">of web work tracked through the studio.</p><p class="d">7 principals across 6 teams.</p></div>
        <div class="we-res rise d3"><p class="l">Standards</p><p class="num">15</p><p class="d">Figma components in 90 days, used across all teams.</p><p class="d">100% of new designs on standard breakpoints.</p></div>
        <div class="we-res rise d4"><p class="l">Navigation</p><p class="num">$5M+</p><p class="d">projected a year, up to $7.3M, from unified navigation. The case carried into the homepage redesign.</p><p class="d">Direct navigation engagement up nearly 70% on the new homepage.</p></div>
        <div class="we-res rise d5"><p class="l">Vision</p><p class="num">1 month</p><p class="d">to design principles for all of web, from a principal hired to define it.</p><p class="d">A new t-mobile.com homepage, live today.</p></div>
      </div>
    </div>
  </section>`,
    },
  ],
};
